### ISSUE TITLE
Media summary item on Wagtail Dashboard wraps to a new line

### ISSUE THREAD

**Issue by isandunk** [torchbox/wagtailmedia#89] opened 2020-02-21 10:42 UTC
### Issue Summary

Summary stats for Media on Wagtail Dashboard wrap to a new line

### Steps to Reproduce

1. Log in to Wagtail Admin
2. View the dashboard page, which has the stats for pages / images / documents
3. See the addition of "Media files" which is present on a second line

This looks awkward and leaves a lot of empty space. Ideally all icons would fit on one line.
The width of the stats in controlled via css. Currently it is set (via `.summary ul.stats li`) to be `width:33%` of the container, it would be better set at `width:20%`

### Technical details

* Wagtail version: 2.6.2
* `wagtailmedia` version: 0.3.1
* Browser version: Chrome 80.0.3987.106 (Official Build) (64-bit) / Win 10

**Comment by Anish9901** [comment] 2022-01-04 20:02
Hi @zerolab , I am new to open source I have looked into this issue and reproduced it, I would like to work on it. Could you please guide me, do we have to create a hook inside wagtail_hooks.py for adding CSS, or any other way?

**Comment by zerolab** [comment] 2022-01-06 11:28
Given the fact a site may have other summary items, this should not be something we try to force at the package level, but is better tackled in Wagtail itself.

@Anish9901 given the above, and if you're still up for it, I'd attempt to fix that within Wagtail and test with 3, 4, 5, 6 and more summary items ([Wagtail docs](https://docs.wagtail.io/en/stable/reference/hooks.html#construct-homepage-summary-items)) and how that looks like at different screen sizes

**Comment by zerolab** [comment] 2022-02-04 12:46
Going to close this as it something to fix in core rather than wagtailmedia.
Thank you for the report/interest in working on this.

**Closed by zerolab** 2022-02-04 12:46 UTC
Labels: good first issue
